/*
	TABLESPACES E DATA FILES
*/

	• Tablespaces contém os objetos do banco de dados e organizam os arquivos de dados 
	• Hierarquia de armazenamento do Oracle:
		
-- TABLESPACES  - CARACTERISTICAS E TIPOS
	• Uma tablespace pode pertencer a apenas um banco de dados por vez
	• Tablespaces podem ser somente para a leitura ou leitura/gravação 
	• Cada tablespace pode ser composta por mais de um arquivo de dados
	• Um arquivo de dados deve pertencer a apenas uma tablespace
	• A definição das tablespaces e seus arquivos de dados é feita na criação do banco (script createdb1.sql)

--TIPOS DE TABLESPACES ESPECIAIS
SYSTEM 	  --Contém o dicionário de dados 
UNDO   	  --Contém segmentos de UNDO 
TEMPORARY --Usado para operações de sort em SQL

--VERIFICAR INFORMAÇÕES SOBRE OS ARQUIVOS DE DADOS
SELECT FILE#,NAME,STATUS,ENABLED FROM V$DATAFILE;
SELECT FILE_NAME,TABLESPACE_NAME,ONLINE_STATUS , BYTES, MAXBYTES  FROM DBA_DATA_FILES;

--VERIFICAR INFORMAÇÕES SOBRE TABLESPACES 
SELECT TS#, NAME FROM V$TABLESPACE; 
SELECT * FROM DBA_TABLESPACES; 

--VERIFICAR OS TEMP FILES EXISTENTES
SELECT NAME,STATUS,ENABLED,BYTES FROM V$TEMPFILE;
SELECT FILE_NAME, TABLESPACE_NAME, STATUS, BYTES, MAXBYTES FROM DBA_TEMP_FILES;

--VERIFICANDO ESPAÇO EM TABLESPACE TEMP
SELECT * FROM DBA_TEMP_FREE_SPACE;


--CRIANDO TABLESPACE NOVA
	• Podemos criar uma tablespace e seus arquivos de dados com o comando CREATE TABLESPACE
	• Indique o nome da tablespace, os arquivos de dados e as opções de crescimento
	
	• Nota: o comando CREATE TABLESPACE é complexo e possui diversas opções. Em caso de dúvida consulte a documentação

CREATE TABLESPACE SCI_CNV_SERVICO LOGGING DATAFILE 
   DATAFILE 'D:\ORACLE\ORADATA\BAURU\SCI_CNV_SERVICO.DBF' SIZE 1000K REUSE
   AUTOEXTEND ON NEXT 500K MAXSIZE UNLIMITED;
   
----CRIANDO TABLESPACE TEMP NOVA
CREATE TEMPORARY TABLESPACE "SCI_CNV_AUX_TEMP"
TEMPFILE 'D:\ORACLE\ORADATA\BAURU\SCI_CNV_AUX_TEMP.DBF' SIZE 5M AUTOEXTEND ON;

-- CRIANDO UMA 2º TABLESPACE TEMPORÁRIA
CREATE TEMPORARY TABLESPACE TEMP2
TEMPFILE '/U02/ORADATA/TESTDB/TEMP2_01.DBF' SIZE 5M REUSE
AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

--ALTERANDO TABLESPACES PARA OFFLINE E ONLINE
	• Podemos desativar (offline) uma tablespace temporariamente para resolver algum problema
	ALTER TABLESPACE MYTABLESPACE OFFLINE; -- TODOS OS OBJETOS CRIADOS NA TABLESPACE FICAM INDISPONIVEIS
	ALTER TABLESPACE MYTABLESPACE ONLINE;

-- ALTERANDO A TABLESPACE TEMPORáRIA DE TEMP PARA TEMP2
ALTER DATABASE DEFAULT TEMPORARY TABLESPACE TEMP2;

--ADICIONANDO UM NOVO DATAFILE A UMA TABLESPACE  (Addind Datafile to existing Tablespace:)
ALTER TABLESPACE USERS ADD DATAFILE 'D:\ORACLEXE\ORADATA\XE\USERS_2.DBF' SIZE 50M;

-- REDIMENSIONAR TAMANHO DE UM DATAFILE EM UMA TABLESPACE  (Resizing Datafile)
ALTER DATABASE DATAFILE 'D:\ORACLEXE\ORADATA\XE\USERS.DBF' RESIZE 200M;         --DATAFILE PARA TABLESPACES NORMAL
ALTER DATABASE TEMPFILE 'D:\ORACLEXE\ORADATA\XE\USERS.DBF' RESIZE 1000M; --1g   --TEMPFILE PARA TABLESPACES TEMP

--MOVER UM DATAFILE PARA UMA NOVA PASTA
ALTER TABLESPACE USERS OFFLINE; 
Crie a pasta /ora_place/oradata/orcl/myts/ 
Copie o arquivo /ora_place/oradata/orcl/USERS.DBF  para /ora_place/oradata/orcl/USERS.DBF
ALTER TABLESPACE USERS RENAME DATAFILE '/ora_place/oradata/orcl/USERS.dbf' TO '/ora_place/oradata/orcl/myts/USERS.dbf';        
ALTER TABLESPACE USERS ONLINE; 

--DROPANDO A TABLESPACE
DROP TABLESPACE TEMP INCLUDING CONTENTS AND DATAFILES;